parameters:
  - name: armSubscriptionId
    type: string
  - name: armClientId
    type: string
  - name: armClientSecret
    type: string
  - name: armTenantId
    type: string
  - name: workingDirectory
    type: string
    default: 'System.DefaultWorkingDirectory'
  - name: deploymentDirectory
    type: string
    default: 'System.DefaultWorkingDirectory'
  - name: terraformPlanCliOptions
    type: string

steps:
- bash: |
    terraform version
    terraform plan ${{ parameters.terraformPlanCliOptions }}
  displayName: 'Terraform Plan'
  continueOnError: false
  workingDirectory: ${{ parameters.workingDirectory }}
  env:
    ARM_SUBSCRIPTION_ID: ${{ parameters.armSubscriptionId }}
    ARM_CLIENT_ID:       ${{ parameters.armClientId }}
    ARM_CLIENT_SECRET:   ${{ parameters.armClientSecret }}
    ARM_TENANT_ID:       ${{ parameters.armTenantId }}